version: "3"

services:
  # TODO evaluate this downstream image. This allows the backend to assume that the storage buckets
  # already exist in minio, which may or may not be a fair assumption for users in a production environment.
  # would users prefer that assumption be made and they have to manually set up the buckets? the bucket names
  # are configurable for the cryostat application so there is no forced name collision, so perhaps
  # automatic creation of the buckets on startup is OK.
  # minio:
  #   image: docker.io/bitnami/minio:latest
  #   hostname: minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: minioroot
  #     MINIO_ROOT_PASSWORD: minioroot
  #     MINIO_DEFAULT_BUCKETS: archivedrecordings
  #   volumes:
  #     - minio_data:/data
  #     - minio_certs:/certs
  minio:
    image: docker.io/minio/minio:latest
    hostname: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
    volumes:
      - minio_data:/data
      - minio_certs:/certs
    labels:
      kompose.service.expose: "minio"
  db:
    image: quay.io/cryostat/cryostat3-db:latest
    build: ./db
    command: -c encrypt.key=${PG_ENCRYPT_KEY:-REPLACEME}
    hostname: db
    expose:
      - "5432"
    environment:
      POSTGRES_USER: cryostat3
      POSTGRES_PASSWORD: cryostat3
    volumes:
      - postgresql:/var/lib/postgresql/data
  db-viewer:
    depends_on:
      - db
    image: docker.io/dpage/pgadmin4:6
    hostname: db-viewer
    ports:
      - "8989:8989"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cryostat.io
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 8989
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./smoketest/compose/servers.json:/pgadmin4/servers.json:z
      # - ./smoketest/compose/pgpass:/pgpass:z
  cryostat:
    depends_on:
      - db
      - minio
    image: quay.io/cryostat/cryostat3:latest
    hostname: cryostat3
    expose:
      - "9091"
    ports:
      - "8181:8181"
    labels:
      kompose.service.expose: "cryostat"
    environment:
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: cryostat3
      QUARKUS_DATASOURCE_PASSWORD: cryostat3
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cryostat3
      QUARKUS_MINIO_URL: http://minio:9000
        # create access key in minio console by visiting http://localhost:9001
        # `podman-compose up minio` may be useful to start minio first to create
        # these secrets, then `export MINIO_ACCESS=abcd ; export MINIO_SECRET=1234 ; podman-compose up`
      QUARKUS_MINIO_ACCESS_KEY: ${MINIO_ACCESS:-minioroot}
      QUARKUS_MINIO_SECRET_KEY: ${MINIO_SECRET:-minioroot}
      CRYOSTAT_JDP_ENABLED: "true"
      JAVA_OPTS_APPEND: "-XX:+FlightRecorder -XX:StartFlightRecording=name=onstart,settings=default,disk=true,maxage=5m -Dcom.sun.management.jmxremote.autodiscovery=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.rmi.port=9091 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false"
  sample-app:
    image: quay.io/andrewazores/vertx-fib-demo:0.9.1
    environment:
      HTTP_PORT: 8081
      JMX_PORT: 9093
    ports:
      - "8081:8081"
  quarkus-test-agent:
    image: quay.io/andrewazores/quarkus-test:latest
    hostname: quarkus-test-agent
    ports:
      - "9977:9977"
      - "10010:10010"
    environment:
      JAVA_OPTS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/deployments/app/cryostat-agent.jar"
      QUARKUS_HTTP_PORT: 10010
      ORG_ACME_CRYOSTATSERVICE_ENABLED: false
      CRYOSTAT_AGENT_APP_NAME: quarkus-test-agent
      CRYOSTAT_AGENT_WEBSERVER_HOST: quarkus-test-agent
      CRYOSTAT_AGENT_WEBSERVER_PORT: 9977
      CRYOSTAT_AGENT_CALLBACK: http://quarkus-test-agent:9977/
      CRYOSTAT_AGENT_BASEURI: http://cryostat:8181/
      CRYOSTAT_AGENT_SSL_TRUST_ALL: true
      CRYOSTAT_AGENT_SSL_VERIFY_HOSTNAME: false
      CRYOSTAT_AGENT_AUTHORIZATION: Basic dXNlcjpwYXNz # "Basic $(echo -n user:pass | base64)"
      CRYOSTAT_AGENT_HARVESTER_PERIOD_MS: 30000
      CRYOSTAT_AGENT_HARVESTER_MAX_FILES: 3
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_AGE_MS: 60000
      CRYOSTAT_AGENT_HARVESTER_EXIT_MAX_SIZE_B: 153600 # "$(echo 1024*150 | bc)"

volumes:
  minio_data:
    driver: local
  minio_certs:
    driver: local
  postgresql:
    driver: local
  pgadmin:
    driver: local
