version: "3.7"

services:
  db:
    image: quay.io/cryostat/cryostat3-db:latest
    build: ../db
    command: -c encrypt.key=REPLACEME
    hostname: db
    expose:
      - "5432"
    environment:
      POSTGRES_USER: cryostat
      POSTGRES_PASSWORD: cryostat
  cryostat:
    depends-on:
      - db
    image: quay.io/cryostat/cryostat3:latest
    ports:
      - "8181:8181"
    environment:
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: cryostat
      QUARKUS_DATASOURCE_PASSWORD: cryostat
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cryostat
