version: "3.7"

services:
  db:
    image: quay.io/cryostat/cryostat3-db:latest
    build: ../db
    command: -c encrypt.key=REPLACEME
    hostname: db
    expose:
      - "5432"
    environment:
      POSTGRES_USER: cryostat3
      POSTGRES_PASSWORD: cryostat3
  cryostat:
    depends-on:
      - db
    image: quay.io/cryostat/cryostat3:latest
    expose:
      - "9091"
    ports:
      - "8181:8181"
    environment:
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: cryostat3
      QUARKUS_DATASOURCE_PASSWORD: cryostat3
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cryostat3
      CRYOSTAT_JDP_ENABLED: true
      JAVA_OPTS_APPEND: "-XX:+FlightRecorder -Dcom.sun.management.jmxremote.autodiscovery=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.rmi.port=9091 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false"
