version: "3"
services:
  s3:
    image: docker.io/minio/minio:latest
    hostname: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioroot}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioroot}
      MINIO_DEFAULT_BUCKETS: archivedrecordings
    volumes:
      - minio_data:/data
      - minio_certs:/certs
    labels:
      kompose.service.expose: "minio"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  minio_data:
    driver: local
  minio_certs:
    driver: local
  postgresql:
    driver: local
  pgadmin:
    driver: local
